### ISSUE TITLE
Plans for Loupedeck Live S?

### ISSUE THREAD

**Issue by Julusian** [foxxyz/loupedeck#11]
Loupedeck have a crowdfunder for a new model https://www.indiegogo.com/projects/loupedeck-live-s-customizable-streaming-console/x/8975848#/

Do you have plans to support it here?
Are you interested in a PR to support it?

I have placed an order for one, intending to do some reverse engineering as needed

**Comment by foxxyz** [comment]
Absolutely, it looks like a great device and I'd love to support it.

To accept a PR I'd need to test it though, so perhaps somebody can sponsor development by shipping me one! 😃

**Comment by foxxyz** [comment]
Closing for now - let me know if you get a chance to test on a S or can procure one for development!

**Comment by MostHated** [comment]
I tested out the "simple" example on my Live S I just received, and it seemed to work well. The other example connected, but then nothing else happened, but just seeing the simple example work is enough for me. :+1:

**Comment by foxxyz** [comment]
That's great news, @MostHated. Hopefully I'll get to try it out myself soon and add real compatibility.
