### ISSUE TITLE
Razer Stream Controller

### ISSUE THREAD

**Issue by linkshadowelf** [foxxyz/loupedeck#25]
Is this project designed to work with the Razer Stream Controller? Or is the stream controller just different enough from a regular LoupeDeck Live that it will kind of work as is?

In minimal testing, I was able to manually connect to it (the auto discover wasn't able to find it) forcing the Loupedeck Live class. Using a slightly modified version of the simple example, it was able to read the touch screen, trigger the vibration, and work with the knobs. The buttons were able to change color once, but I have yet to figure out why they are not changing. touch.key is also undefined.

Additionally, I attempted the slide example, but the touchscreen's appearance did not change outside of the default appearance (a set of rotated semicircles).

Finally, when the app is closed, it takes about 30 seconds or more for the stream controller to be released/disconnected from the application despite running loupedeck.close().

All testing was done on PopOS 22.04 LTS (Debian based). Thank you!

**Comment by foxxyz** [comment]
Oooh, this is cool. I did not know Razer partnered with Loupedeck to do a rebranded version of the Live!

I definitely did not test compatibility for it, but it sounds that from your testing that there is some compatibility. Thank you for  doing that!

I would love to add real compatibility if I can get my hands on a physical device. I'd expect the changes to be pretty minor, but from your comments it seems like they are using a different coordinate system and perhaps different command bytes for writing to the screen and button colors.

Thanks for putting this on my radar, and let me know if there's a way you can get me a physical device!

**Comment by linkshadowelf** [comment]
While I can't get you the physical device (yet), I may be able to assist from the one I have. If there's any test scripts or code I can edit to test the device, let me know. I'm still relatively new to node, but willing to learn. (Most of my experience has been with Foundry VTT in an attempt to make a few custom systems for it).

**Comment by Julusian** [comment]
Yeah as far as I'm aware there is very little difference between them. In my code I am handling them identically. 
But the main difference to what you have now is that the screens must all be addressed as one large `0x4d`. In my testing, this also works for the live with the 0.2.5(?) firmware, so I adopted this approach for these too to keep it simpler.

There is also the [razer stream controller x](https://www.razer.com/gb-en/streaming-accessories/razer-stream-controller-x). This is again a subset of existing functionality, the button presses are the same as the circle buttons on other models, and it has a single lcd segment

**Comment by asdf23** [comment]
Razer locks their keyboard down where you cannot use it without logging in.

Anything associated with company is spyware garbage

**Comment by foxxyz** [comment]
@linkshadowelf I added support, try it out and open a new issue if you find any problems!
