### ISSUE TITLE
Razer Steam Controller X

### ISSUE THREAD

**Issue by henriclaytor** [foxxyz/loupedeck#28]
Error: Device with product ID 3337 not yet supported! Please file an issue at https://github.com/foxxyz/loupedeck/issues. Reattempting in 3 seconds...

For the Razer Steam Controller X

  static productId = 0x0d09
  static vendorId = 0x1532

**Comment by foxxyz** [comment]
This device is more like an Elgato (rather than a Loupedeck clone, like the regular Razer Stream Controller), so it doesn't make much sense to support it in this library.

Have you checked if there's an Elgato-compatible module that supports it?

**Comment by Julusian** [comment]
I have one, it is a loupedeck (I am pretty sure it uses the loupedeck software, if you go that route) and follows almost identical protocol to the other loupedeck devices.
It is unlikely that any streamdeck library will support it (mine doesn't) purely because it is a serial rather than hid device.

**Comment by foxxyz** [comment]
@Julusian Thank you, I didn't know they are still using loupdeck firmware in this unit as well. In that case it may make sense to support it.

I will keep this open and try to obtain one for testing.
