### ISSUE TITLE
New Loupedeck Live with 0.2.11 - cannot draw to screen

### ISSUE THREAD

**Issue by Pero-Moretti** [foxxyz/loupedeck#29]
Hi there, I've just bought a Loupedeck live and was excited to play around with this under linux, the simple example works fine but when I added a simple test to see if I could draw to the screen, nothing happens ... I tried using the canvas callback example, and also just doing:

    const arr = new Uint8Array(32400)
    for (let i = 0; i < 194400; i++) {
      arr[i] = 127
    }
    const b = Buffer.from(arr)
    loupedeck.drawBuffer({ id: 'left' }, b)

from the connect callback - neither do anything at all... (was expecting the above to just fill the left screen in grey)...

Have you got it working on 0.2.11? Do you think they changed the command for this firmware version?

**Comment by Julusian** [comment]
I've fixed this bug in a different library. 

There appears to be a 'Ver: v2.00' devices (according to the label on the rear) which have a newer firmware than v1.x devices. (0.2.11 vs 0.2.5).

These devices require drawing to be done with the same unified display `'\x00M'` in the same way as the 'Razer Stream Controller'.  
It is also worth noting that the same unified display behaviour does work on the v1.x loupedeck live when running firmware 0.2.5, so there is potential for keeping the code simpler to do the same for both. (I havent tried firmware 0.1)

**Comment by foxxyz** [comment]
So much for semver, haha!

@Julusian thanks, this is super helpful - it does indeed work on 0.2.5 and on 0.1.x also. 

@Pero-Moretti thanks for reporting this - I'll release a new version shortly that should fix this. I tried to see if I could update mine to 0.2.11, but Loupedeck says I'm already on the latest, so if you run into any more issues using 0.2.11, let me know.

(and if you don't, let me know too! Then i'll add 0.2.11 to the list of supported firmware versions in the docs)

**Comment by foxxyz** [comment]
Fix released in [v5.0.0](https://github.com/foxxyz/loupedeck/releases/tag/v5.0.0). Let me know if you run into more issues!
