### ISSUE TITLE
Sorry, not an issue just a question

### ISSUE THREAD

**Issue by AncientMecha** [foxxyz/loupedeck#35]
Hello! Sorry to post this in issues, but I couldn't find another way to get in touch.

I've been searching for anyone developing a frontend for this project, but haven't come across anything yet.

Do you know of any such projects in development that I could look into?

Thanks, and sorry again.

**Comment by foxxyz** [comment]
There's a web front-end in [`examples/web`](https://github.com/foxxyz/loupedeck/tree/master/examples/web) that you can try out. Is that what you mean?

**Comment by AncientMecha** [comment]
I completely missed that, thank you I'll have a look at it.

**Comment by foxxyz** [comment]
No problem :)
