### ISSUE TITLE
Have to connect (run the program) twice after closing the device.

### ISSUE THREAD

**Issue by Determinant** [foxxyz/loupedeck#36]
I encountered a very reproducible issue with my device (both with my code and the "simple" example in this library): it works on the first time (using `discover()`), then it hangs when you rerun the program. And then, if you run it again, it will connect normally. This is not a big issue, but kinda annoying because it means you have to run program twice (run it once, it hangs, and kill it and run again) to be connected, except for the first time. (Great project BTW, I really like it!)

And I noticed that on my Razer Stream Controller, when the connect attempt hangs, the light on buttons seems to be reset (instead of green), so then the next run is fine.

**Comment by foxxyz** [comment]
Hi @Determinant!

Can you give me some more info on your environment? E.G. OS, Node version, devices you've tested with?

I just tested it with a Live S and was unable to reproduce it (see 3 consecutive connections of the `simple` example below). Does it only happen with the Razer Stream Controller?

```
[21:23] loupedeck/examples/simple > ./index.mjs
✅ Connected to Loupedeck Live S at /dev/tty.usbmodem101
Device serial number <REDACTED>, software version 0.1.4
^C
[21:23] loupedeck/examples/simple > ./index.mjs
✅ Connected to Loupedeck Live S at /dev/tty.usbmodem101
Device serial number <REDACTED>, software version 0.1.4
^C
[21:23] loupedeck/examples/simple > ./index.mjs
✅ Connected to Loupedeck Live S at /dev/tty.usbmodem101
Device serial number <REDACTED>, software version 0.1.4
```

**Comment by Determinant** [comment]
I tried it on Linux and Windows, using node v22.6.0 (and also tried v17 before I realized that I needed to upgrade my nodejs lol).

**Comment by foxxyz** [comment]
> I tried it on Linux and Windows

What specific versions / distributions? I have a Windows 11 machine and an Ubuntu 24.04 machine that I can test with, I'd like to get as close to your environment as possible to see if I can reproduce it.

Also, let me know if it's only the Razer Stream Controller or also other devices.

**Comment by foxxyz** [comment]
I was able to reproduce it on Arch Linux - I will investigate!

**Comment by Determinant** [comment]
Unfortunately I don't have other Loupedeck decides, but yeah I'm using Arch Linux, and also was able to reproduce it on Windows (through PowerShell).

**Comment by foxxyz** [comment]
@Determinant try [v6.0.1](https://www.npmjs.com/package/loupedeck/v/6.0.1) and see if it solves the issue for you!

**Comment by Determinant** [comment]
That works! Thanks for the fix.
