### ISSUE TITLE
https://registry.npmjs.org/looupedeck

### ISSUE THREAD

**Issue by Algolian** [foxxyz/loupedeck#37]
Hi. Im trying to build this on Fedora41.
~/gits/loupedeck/fox/loupedeck$ npm install looupedeck
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @typescript-eslint/utils@7.10.0
npm warn Found: eslint@9.4.0
npm warn node_modules/eslint
npm warn   peer eslint@">=9.0.0" from @appliedminds/eslint-config@2.0.1
npm warn   node_modules/@appliedminds/eslint-config
npm warn     dev @appliedminds/eslint-config@"^2.0.1" from the root project
npm warn   5 more (@eslint-community/eslint-utils, eslint-plugin-jest, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^8.56.0" from @typescript-eslint/utils@7.10.0
npm warn node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils
npm warn   @typescript-eslint/utils@"^6.0.0 || ^7.0.0" from eslint-plugin-jest@28.6.0
npm warn   node_modules/eslint-plugin-jest
npm warn
npm warn Conflicting peer dependency: eslint@8.57.1
npm warn node_modules/eslint
npm warn   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.10.0
npm warn   node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils
npm warn     @typescript-eslint/utils@"^6.0.0 || ^7.0.0" from eslint-plugin-jest@28.6.0
npm warn     node_modules/eslint-plugin-jest
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/looupedeck - Not found
npm error 404
npm error 404  'looupedeck@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/.npm/_logs/2024-12-29T10_17_27_401Z-debug-0.log

Fedora41 is using node22 > node18+ 
Any ideas what can be wrong?

**Comment by foxxyz** [comment]
`npm install loupedeck` is for installing it as a library or dependency of another project, but it looks like you cloned the repository locally, which means you can just run `npm install` in the repository directory to play around with it.

Note that there's a typo in the name of the library you're trying to install: `loupedeck` not `looupedeck`.

Let me know if you need additional help!

**Comment by Algolian** [comment]
Tnx. Some progress at least. Will continue next year...
