### ISSUE TITLE
Loupedeck Live Firmware v0.2.5 breaks library

### ISSUE THREAD

**Issue by jonwyett** [foxxyz/loupedeck#6]
"The firmware version 0.2.5 changes the way Loupedeck CT / Live creates a connection with your computer. It will no longer be a network device, but it will use serial communication for sending data between your computer and the device."

https://support.loupedeck.com/firmware

**Comment by foxxyz** [comment]
Fun! Will investigate supporting this, and at least add a note regarding firmware versions if we can't.
