### ISSUE TITLE
Issue with drawCanvas

### ISSUE THREAD

**Issue by chidoli** [foxxyz/loupedeck#9]
Just wondering if this is happening on others as well.

With top of the branch supporting firmware 0.2.5, I was able to run "simple.js" example to check touch and dial actions. I can see that physical buttons cycling thru different colors. But the screen has nothing and plain black. Anyone seeing the same issue?

**Comment by chidoli** [comment]
My suspicion is on brightness, but was not able to confirm yet.

**Comment by foxxyz** [comment]
I am able to reproduce a black screen by inserting `loupedeck.setBrightness(0)` on [line 10 of the simple example](https://github.com/foxxyz/loupedeck/blob/master/examples/simple/index.js#L10), but it shouldn't do this unless you had maybe previously set the brightness to 0 using the official Loupedeck sofware.

Actually, this made me discover a small issue with setting `.setBrightness(1)` - it doesn't seem to work if brightness had been set to zero previously.

Try v1.3.1 and add `loupedeck.setBrightness(1)` in the example to see if that changes anything for you.

**Comment by chidoli** [comment]
Interesting, I have tried to set brightness at the same line just like the updated simple/index.js but didn't work. But I can confirm that v1.3.1 is working. I didn't set brightness to 0 and not sure why it had issues.

Thanks for helping out!

**Comment by chidoli** [comment]
And thanks for really exciting project! Wonder how you have figured the serial communication details like HEADERs.
